// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClientselectController from "./clientselect_controller"
application.register("clientselect", ClientselectController)

import FormValidationController from "./form_validation_controller"
application.register("form-validation", FormValidationController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvoicesChartController from "./invoices_chart_controller"
application.register("invoices-chart", InvoicesChartController)

import ItemselectController from "./itemselect_controller"
application.register("itemselect", ItemselectController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import PaidVsUnpaidChartController from "./paid_vs_unpaid_chart_controller"
application.register("paid-vs-unpaid-chart", PaidVsUnpaidChartController)

import RecalculateController from "./recalculate_controller"
application.register("recalculate", RecalculateController)

import RemoveitemController from "./removeitem_controller"
application.register("removeitem", RemoveitemController)

import SelectController from "./select_controller"
application.register("select", SelectController)
